version: '3.4'
networks:
  k6:
services:
  streamlitapp:
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - k6
    volumes:
      - shared-data:/app
    ports:
      - "8501:8501"
    depends_on:
      k6-test:
        condition: service_healthy
        restart: true

  k6-test:
    image: grafana/k6:latest
    networks:
      - k6
    ports:
      - "6565:6565"
    volumes:
      - shared-data:/app
    
volumes:
  shared-data:

    